# Generated by Django 4.1.5 on 2023-01-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctionlisting_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='product_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=64),
        ),
    ]
