# Generated by Django 4.1.5 on 2023-01-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auctionlisting_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_count',
            field=models.IntegerField(default=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='category_details',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
