# Generated by Django 4.1.5 on 2023-01-31 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_category_category_count_category_category_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_count',
        ),
    ]
