# Generated by Django 4.1.5 on 2023-01-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_category_category_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
