# Generated by Django 4.1.5 on 2023-01-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_category_category_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_details',
            field=models.TextField(max_length=128, null=True),
        ),
    ]
