# Generated by Django 4.1.5 on 2023-01-31 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_category_category_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_count',
        ),
    ]
