# Generated by Django 4.1.5 on 2023-02-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_alter_auctionlisting_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bids',
        ),
    ]
