# Generated by Django 4.1.5 on 2023-02-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_delete_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='product_name',
            field=models.CharField(max_length=128),
        ),
    ]
