# Generated by Django 4.1.5 on 2023-02-06 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_alter_auctionlisting_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='product_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_price', to='auctions.bid'),
        ),
    ]
