# Generated by Django 4.1.5 on 2023-02-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_auctionlisting_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
